Khushboo Org/force-app/main/default/objects/User/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Khushboo Org/force-app/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
                <default>true</default>
                <label>Employee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Khushboo Org/force-app/main/default/classes/EMSEditEmployee.cls
public class EMSEditEmployee 
{
    public Id opt
    {
        get;
        set;
    }
 
   public User user1;
    
    public List<SelectOption> newList= new List<selectOption>();
    
    public list<selectOption> getUserList()
    {
        newList.clear();
        newList.Add(new SelectOption('','--Select--'));
        for(User us:[select id,Name from User where Type__c='Employee'])
        {
            newList.Add(new SelectOption(us.Id, us.Name));
        }
     
        return newList;
    }
    
    public User getUser1()
    {
        if(opt!=null)
        {
        User1=[Select FirstName,LastName,Email, Username,Street, City, State, PostalCode, Country, IsActive, Salary__c, Phone from User where Id=:opt];
        }
        return User1;
    }
}